{% set name = "lvis" %}
{% set version = "0.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/lvis-{{ version }}.tar.gz
    sha256: 55aeeb84174abea2ed0d6985a8e93aa9bdbb60c61c6db130c8269a275ef61a6e
    patches:
      - 42.patch
  - path: requirements.txt

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 2

requirements:
  build:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - cycler >=0.10.0
    - cython >=0.29.12
    - kiwisolver >=1.1.0
    - matplotlib-base
    - numpy
    - opencv
    - pyparsing >=2.4.0
    - python >={{ python_min }}
    - python-dateutil >=2.8.0
    - six
    - pycocotools

test:
  imports:
    - lvis
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/lvis-dataset/lvis-api
  doc_url: https://www.lvisdataset.org/
  summary: Python API for LVIS dataset.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
